#!/usr/bin/env ruby
# encoding: utf-8

require 'bundler/setup'
require 'ruby-error-logger'

c = PEL::CONFIG
c[:logfile] = 'log/proxyerror.log'
#c[:debug] = true
#c[:write_queue_size] = 4
#c[:read_queue_size] = 4
#c[:rotate_time] = 10
#c[:rotate_size] = (c[:rotate_size] / 10) / 2
#c[:throttle_send] = 0.01

rotator = PEL::Rotator.new.run

